[package]
name = "postman_collection"
version = "0.1.0"
authors = ["Sebastian Mandrean <sebastian.mandrean@gmail.com>"]
description = "A Postman Collection serialization & deserialization library."
license = "MIT"
repository = "https://github.com/mandrean/postman-collection-rs"
documentation = "https://docs.rs/postman_collection"
readme = "README.md"
keywords = ["postman", "collection", "postman-collection", "serialization", "deserialization"]

[badges]
travis-ci = { repository = "mandrean/postman-collection-rs" }

[dependencies]
error-chain = "0.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["raw_value"] }
serde_yaml = "0.8"
semver = "0.9"
url = "1.7"
url_serde = "0.2"

[dev-dependencies]
glob = "0.2"
